name: build-android-tun2socks
on:
  workflow_dispatch:

jobs:
  build-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch sources
        run: git clone https://github.com/xjasonlyu/tun2socks src

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d

      - name: Build arm64-v8a (PIE)
        run: |
          cd src
          export API=21
          export GOOS=android
          export GOARCH=arm64
          export CGO_ENABLED=1
          export CC=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android${API}-clang
          go env
          # Важно: Android требует PIE
          go build -v -trimpath -ldflags "-s -w" -buildmode=pie -o tun2socks-arm64-v8a ./cmd/tun2socks
          ls -lh tun2socks-arm64-v8a

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tun2socks-android
          path: src/tun2socks-arm64-v8a
